#!/bin/bash
MODE="$1"

if [ "$EUID" -ne 0 ]; then
  echo "Lance avec sudo."
  exit 1
fi

case "$MODE" in
  performance)
    sysctl -w vm.swappiness=5 >/dev/null 2>&1 || true
    sysctl -w vm.vfs_cache_pressure=50 >/dev/null 2>&1 || true
    echo "Mode performance NL activé."
    ;;
  gaming)
    sysctl -w vm.swappiness=5 >/dev/null 2>&1 || true
    sysctl -w kernel.sched_autogroup_enabled=1 >/dev/null 2>&1 || true
    echo "Mode gaming NL activé."
    ;;
  *)
    echo "Modes : performance, gaming"
    ;;
esac
